# Generated by Django 5.0.6 on 2024-06-24 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='user id')),
                ('referrer_id', models.CharField(max_length=100, verbose_name='Айди реферальк')),
                ('username', models.CharField(max_length=100, verbose_name='username')),
            ],
            options={
                'verbose_name_plural': 'Бизнес пользователи',
            },
        ),
        migrations.CreateModel(
            name='UserCklient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='user id')),
                ('referrer_id', models.CharField(max_length=100, verbose_name='Айди Реферальки')),
                ('username', models.CharField(max_length=100, verbose_name='username')),
            ],
            options={
                'verbose_name_plural': 'Пользователи клиента',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=155, verbose_name='Район')),
                ('pansionat', models.CharField(max_length=155, verbose_name='Название пансионата')),
                ('type_accommodation', models.CharField(max_length=155, verbose_name='Тип размещения')),
                ('facilities', models.CharField(max_length=155, verbose_name='Удобства')),
                ('quantities', models.CharField(max_length=155, verbose_name='Количества')),
                ('price', models.CharField(max_length=155, verbose_name='Цена')),
                ('phone_number', models.CharField(max_length=155, verbose_name='Номер телефона')),
                ('photos', models.TextField(verbose_name='Фотографии')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активный')),
                ('referrer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.userbusiness', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name_plural': 'Отели Бизнесов',
            },
        ),
        migrations.CreateModel(
            name='Cklient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=155, verbose_name='Район')),
                ('date', models.CharField(max_length=155, verbose_name='Дата Заезда')),
                ('comment', models.TextField(verbose_name='Комментраия')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.usercklient', verbose_name='Пользователи')),
            ],
            options={
                'verbose_name_plural': 'Бронирование Клиента',
            },
        ),
    ]
